# -*- coding: utf-8 -*-
"""DataSales.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1v3uQynbEUVEDkaYfL7F5fn48dM4vbm6o

Pandas library
"""

import pandas as pd

"""Creating a Pandas DataFrame

Importing the data from CSV file to a Pandas DataFrame
"""

data_df = pd.read_csv('data.csv')

"""Inspecting the DataFrame"""

data_df.head()

#finding the number of row and columns
data_df.shape

data_df.tail()

data_df.info()

#findinf the number of missing values
data_df.isnull().sum()

#counting the values based on the labels
data_df.value_counts('Product')

"""Statistical Measures"""

#count number of values
data_df.count()

# minimum values
data_df.min()

# maximum value
data_df.max()

#all the statistical measures about the DataFrame
data_df.describe()

"""Manipulating a DataFrame"""

data_df.head()

# removing a row
data_df.drop(index=0, axis=0)

# drop a column
#data_df.drop(columns='value', axis=1)

# locating a row using the index value
data_df.iloc[2]

## Accessing a specified element
data_df.at[2,'Sales']

## Accessing a specified element using iat
data_df.iat[2,2]

"""Correlation:

1. Positive Correlation
2. Negative Correlation
"""

## Dataframe
## create a Dataframe from a dictionary oof list

data={
    'Name':['Mary','John','Jack'],
    'Age':[25,30,45],
    'City':['UK','New York','Florida']
}
df=pd.DataFrame(data)
print(df)

df

## Adding a column
df['Salary']=[50000,60000,70000]
df

## Add age to the column
df['Age']=df['Age']+1
df

## fecth the first 5 rows
df.head(5)

df.info()

df.isnull().any()

df.isnull().sum()

## Renaming Columns
df=df.rename(columns={'Date':'Sales Date'})
df.head()

df['New Sales']=df['Sales'].apply(lambda x:x*2)
df.head()

grouped_mean=df.groupby('Product')['Sales'].mean()
print(grouped_mean)

grouped_sum=df.groupby(['Product','Region'])['Sales'].sum()
print(grouped_sum)

## aggregate multiple functions
groudped_agg=df.groupby('Region')['Value'].agg(['mean','sum','count'])
groudped_agg

"""Loading the data from a excel file to a Pandas DataFrame:

pd.read_excel('file path')
Exporting a DataFrame to a csv file
"""

data_df.to_csv('boston.csv')